### ISSUE TITLE
Python client MsgPrint overly strict about terminations

### ISSUE THREAD

**Issue by mookerji** [swift-nav/libsbp#135]
From http://zazu.ci.swiftnav.com/job/piksi_firmware_Log_Analysis/15812/console, it appears that Construct (as used by the Python client) is strict about terminations on C strings. Perhaps it should greedy glob whatever's in the rest of the buffer if the payload is a variable length string?

```shell

Installed /var/lib/jenkins/jobs/piksi_firmware_Log_Analysis/workspace/testing_env/lib/python2.7/site-packages/sbp_log_analysis-0.22-py2.7.egg
Processing dependencies for sbp-log-analysis==0.22
Finished processing dependencies for sbp-log-analysis==0.22
python piksi/test_dual_novatel.py $LOG1
+ python piksi/test_dual_novatel.py serial-link-20150428-084729.log.json

Starting log tests...
Traceback (most recent call last):
  File "piksi/test_dual_novatel.py", line 44, in <module>
    main(SBPTestSuite(tests))
  File "/var/lib/jenkins/jobs/piksi_firmware_Log_Analysis/workspace/testing_env/local/lib/python2.7/site-packages/sbp_log_analysis-0.22-py2.7.egg/sbp_log_analysis/runner.py", line 333, in main
    runner.run()
  File "/var/lib/jenkins/jobs/piksi_firmware_Log_Analysis/workspace/testing_env/local/lib/python2.7/site-packages/sbp_log_analysis-0.22-py2.7.egg/sbp_log_analysis/runner.py", line 225, in run
    self.step()
  File "/var/lib/jenkins/jobs/piksi_firmware_Log_Analysis/workspace/testing_env/local/lib/python2.7/site-packages/sbp_log_analysis-0.22-py2.7.egg/sbp_log_analysis/runner.py", line 256, in step
    delta, timestamp, msg = self.log.next()
  File "/var/lib/jenkins/jobs/piksi_firmware_Log_Analysis/workspace/testing_env/local/lib/python2.7/site-packages/sbp/client/loggers/json_logger.py", line 89, in next
    yield (delta, timestamp, self.dispatcher(item))
  File "/var/lib/jenkins/jobs/piksi_firmware_Log_Analysis/workspace/testing_env/local/lib/python2.7/site-packages/sbp/table.py", line 69, in dispatch
    return table[msg.msg_type](msg)
  File "/var/lib/jenkins/jobs/piksi_firmware_Log_Analysis/workspace/testing_env/local/lib/python2.7/site-packages/sbp/logging.py", line 59, in __init__
    self.from_binary(sbp.payload)
  File "/var/lib/jenkins/jobs/piksi_firmware_Log_Analysis/workspace/testing_env/local/lib/python2.7/site-packages/sbp/logging.py", line 74, in from_binary
    p = MsgPrint._parser.parse(d)
  File "/usr/local/lib/python2.7/dist-packages/construct/core.py", line 188, in parse
    return self.parse_stream(BytesIO(data))
  File "/usr/local/lib/python2.7/dist-packages/construct/core.py", line 198, in parse_stream
    return self._parse(stream, Container())
  File "/usr/local/lib/python2.7/dist-packages/construct/core.py", line 670, in _parse
    subobj = sc._parse(stream, context)
  File "/usr/local/lib/python2.7/dist-packages/construct/core.py", line 271, in _parse
    return self.subcon._parse(stream, context)
  File "/usr/local/lib/python2.7/dist-packages/construct/core.py", line 288, in _parse
    return self._decode(self.subcon._parse(stream, context), context)
  File "/usr/local/lib/python2.7/dist-packages/construct/core.py", line 599, in _parse
    raise ArrayError("missing terminator", sys.exc_info()[1])
construct.core.ArrayError: ('missing terminator', FieldError('expected 1, found 0',))
```

https://github.com/swift-nav/libsbp/blob/master/python/sbp/logging.py#L53

**Comment by mfine** [comment]
This has been resolved.
