### ISSUE TITLE
When using only callbacks, "error: unpack requires a string argument of length 5"

### ISSUE THREAD

**Issue by njoubert** [swift-nav/libsbp#325]
The following code snippet crashes:

```
      with PySerialDriver(self.sbp_port, baud=self.sbp_baud) as driver:
        with Handler(Framer(driver.read, None, verbose=True)) as source:
          source.add_callback(self.handle_incoming)
          while True:
            time.sleep(1.0)
```

It crashes with the following error:

```
Exception in thread Handler:
Traceback (most recent call last):
  File "/Applications/Canopy.app/appdata/canopy-1.5.1.2730.macosx-x86_64/Canopy.app/Contents/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/Applications/Canopy.app/appdata/canopy-1.5.1.2730.macosx-x86_64/Canopy.app/Contents/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/njoubert/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/sbp-0.52.1-py2.7.egg/sbp/client/handler.py", line 46, in _recv_thread
    for msg, metadata in self._source:
  File "/Users/njoubert/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/sbp-0.52.1-py2.7.egg/sbp/client/framer.py", line 67, in next
    msg = self._receive()
  File "/Users/njoubert/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/sbp-0.52.1-py2.7.egg/sbp/client/framer.py", line 113, in _receive
    msg_type, sender, msg_len = struct.unpack("<HHB", hdr)
error: unpack requires a string argument of length 5
```

**Comment by njoubert** [comment]
This does NOT happen for the following code snippet:

```
      with PySerialDriver(self.sbp_port, baud=self.sbp_baud) as driver:
        with Handler(Framer(driver.read, None, verbose=True)) as source:
          source.add_callback(self.handle_incoming)
          for msg, metadata in handler.filter(SBP_MSG_OBS, SBP_MSG_BASE_POS_LLH):
            pass
```

**Comment by mookerji** [comment]
Ask @sashamitelman to verify that this fixes the issue with the piksi_bringup stuff as well.

**Comment by sashamitelman** [comment]
@mookerji: That same error still occurs, so this fix doesn't seem to have addressed the problem (at least not for me). FWIW, `git lola` inside my piksi_bringup folder gives me `8e8747c (HEAD -> master, origin/master, origin/HEAD)`.
