### ISSUE TITLE
Broken pyusb dependency on Python 2.x

### ISSUE THREAD

**Issue by Aposhian** [swift-nav/libsbp#982]
It looks like there is a broken dependency with `pyusb` when trying to install on Python 2.x. Of course, Python 2.x is EOL, so I don't expect a fix, but a workaround would be nice. :)

Steps to reproduce:

```bash
docker run ubuntu:bionic bash -c 'apt-get update && apt-get install -yqq python-pip && python2 -m pip install sbp'
```

produces:

```
Collecting sbp
  Downloading https://files.pythonhosted.org/packages/7c/e2/6040516b8f1642e07f154a9a9ad56934b113dbdfa173fe23a0e495756cf3/sbp-3.4.6-py2.py3-none-any.whl (139kB)
Collecting pylibftdi (from sbp)
  Downloading https://files.pythonhosted.org/packages/b0/b5/6413399489ebc7147079b0d6ebbd15cf5fe3b5ae06707cf3606977fa575b/pylibftdi-0.19.0-py2.py3-none-any.whl
Collecting pyftdi~=0.13.4 (from sbp)
  Downloading https://files.pythonhosted.org/packages/0d/84/b6999143d31af4881b17818581ce5f8f213b68aad64726d1336c4e5a84f3/pyftdi-0.13.4.tar.gz (40kB)
Collecting construct==2.9.33 (from sbp)
  Downloading https://files.pythonhosted.org/packages/e9/d3/b53b7d6777aae5505100ca60bde3009df6a6455594b5675b6e359e282762/construct-2.9.33.tar.gz (69kB)
Collecting pyserial (from sbp)
  Downloading https://files.pythonhosted.org/packages/07/bc/587a445451b253b285629263eb51c2d8e9bcea4fc97826266d186f96f558/pyserial-3.5-py2.py3-none-any.whl (90kB)
Collecting pyusb>=1.0.0b1 (from pyftdi~=0.13.4->sbp)
  Downloading https://files.pythonhosted.org/packages/b9/8d/25c4e446a07e918eb39b5af25c4a83a89db95ae44e4ed5a46c3c53b0a4d6/pyusb-1.1.1.tar.gz (74kB)
    Complete output from command python setup.py egg_info:
    /tmp/easy_install-Jof45N/setuptools_scm-6.0.1/src
    <pkg_resources.WorkingSet object at 0x7f58d8b31810>
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-TSm4Tu/pyusb/setup.py", line 117, in <module>
        'Topic :: System :: Hardware :: Hardware Drivers'
      File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 128, in setup
        _install_setup_requires(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 123, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 513, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 774, in resolve
        replace_conflicting=replace_conflicting
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1057, in best_match
        return self.obtain(req, installer)
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1069, in obtain
        return installer(requirement)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 580, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 698, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 724, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 909, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1177, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1163, in run_setup
        run_setup(setup_script, args)
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 253, in run_setup
        raise
      File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-Jof45N/setuptools_scm-6.0.1/setup.py", line 52, in <module>
        return local_scheme
      File "/tmp/easy_install-Jof45N/setuptools_scm-6.0.1/setup.py", line 29, in scm_config
        # (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
      File "/tmp/easy_install-Jof45N/setuptools_scm-6.0.1/src/setuptools_scm/__init__.py", line 8, in <module>
      File "/tmp/easy_install-Jof45N/setuptools_scm-6.0.1/src/setuptools_scm/config.py", line 6, in <module>
      File "/tmp/easy_install-Jof45N/setuptools_scm-6.0.1/src/setuptools_scm/utils.py", line 41
        print(*k)
              ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-TSm4Tu/pyusb/
```

**Comment by jayvdb** [comment]
pyusb is being dragged in by pyftdi ... 

> Collecting pyusb>=1.0.0b1 (from pyftdi~=0.13.4->sbp)

So that might add complexity if we're trying to get a Python 2 compatible version.

pyusb uses setuptools-scm, and latest release of setuptools-scm v6.0.1 doesnt correctly fail on Python 2.  That should be fix in the next release due to https://github.com/pypa/setuptools_scm/commit/83e5902b9306b32470b5529e706bd3f9fd2e868d .

If you first install setuptools_scm v5.0.2 (c.f. https://github.com/pypa/setuptools_scm/blob/main/CHANGELOG.rst#v502) you might be able to get pyusb to install on Python 2.

The next release of pyusb wont support Python 2, per https://github.com/pyusb/pyusb/commit/90d3e0530c5b670685b81e04948017e4b132cb0c , and quite possibly the latest release (pyusb 1.1.1) doesnt support Python 2 either per https://github.com/pyusb/pyusb/commit/52d8784fb3a7ec21be5f6123e18c571484ed4cde .

I do know that pyusb 1.0.2 supported Python 2.  If all else fails, try preinstalling `pip2 install pyusb==1.0.2` and then install libsbp.

**Comment by jayvdb** [comment]
Our CI is testing Python 2.7 via tox, and is [green](https://github.com/swift-nav/libsbp/runs/2565885756) on the latest commit.  Unfortunately the logs do not report the version of pip being used, as I suspect that may be the cause.  It does report that outside of tox, setuptools 56.2.0 is installed, which is the current release.  Again inside tox the version of setuptools isnt shown.  However, inside tox is `virtualenv==20.4.6`, which iirc means that the versions of pip and setuptools are defined here

https://github.com/pypa/virtualenv/blob/24f9a7faa6314b83ccd1fd6469adb90e6b43c3f0/src/virtualenv/seed/wheels/embed/__init__.py#L43
```py
    "2.7": {
        "pip": "pip-20.3.4-py2.py3-none-any.whl",
        "setuptools": "setuptools-44.1.1-py2.py3-none-any.whl",
        "wheel": "wheel-0.36.2-py2.py3-none-any.whl",
    },
```

So presumably installing latest `virtualenv`, and doing the libsbp install inside of a venv should work.  Or installing those versions of pip/setuptools/wheel should work without a venv.

**Comment by Aposhian** [comment]
Preinstalling pyusb==1.0.2 did the trick. Thank you.

**Comment by silverjam** [comment]
Thanks @jayvdb! Feel free to re-open if needed @Aposhian or log a new issue if you run in to a new issue.
